### ISSUE TITLE
TypeError: PNGlib is not a constructor

### ISSUE THREAD

**Issue by bvs90** [stewartlord/identicon.js#12] opened 2016-04-20 17:27 UTC
After the most recent update (for NPM fixes) the above error now occurs. We are not using a module loading system. It seems the PNGLib is not present on window before the main library tries to use it.

**Comment by stewartlord** [comment] 2016-04-20 17:42
Oh no! Very sorry. I will take a look ASAP

**Comment by stewartlord** [comment] 2016-04-20 20:03
Hi @bvs90, I'm having trouble reproducing this. Can you include repro steps?

**Comment by mitar** [comment] 2016-04-21 08:52
@bvs90: Do you have by some accident globally available `module` symbol?

**Comment by bvs90** [comment] 2016-04-27 04:37
@stewartlord @mitar Apologies for the late reply. We are using the library in an Angular project. We are injecting the the library through a factory that just returns $window.identicon and then calling new Identicon() when we need it.

**Comment by bvs90** [comment] 2016-04-27 04:38
We've pegged our bower.json to an earlier commit so we're able to get around the issue but I'd be curious to know if anyone else was having an issue with using the library in Angular.

**Comment by mitar** [comment] 2016-04-27 06:58
Yes, but is there a `window.module` symbol defined in your app? From somewhere else? Because if it is, our detection could misdetect it and then not export it to `window`, which is what you expect.

Can you just go in your app and run `window.module` in the browser console and see if it returns anything?

**Comment by justerhan** [comment] 2016-06-01 21:14
In my case, including pnglib.js prior to identicon.js fixes the issue.

**Comment by stewartlord** [comment] 2016-06-01 21:54
Closing this issue as it seems to be working.

**Closed as completed by stewartlord** 2016-06-01 21:54 UTC
